@startuml
actor User
participant Grensesnitt
participant System
database Database

User -> Grensesnitt: Bli med på valgt arrangement
activate Grensesnitt
Grensesnitt -> System: Registrer bruker for gitt arrangement
activate System
System -> System: Valider forespørsel

alt Suksess
    System -> Database: Lagre registrering
    activate Database
    alt Suksess
    Database -> System: Suksess
    System --> User: send push notifikasjon
    System --> User: Send verifikasjons mail
    System -> Grensesnitt: Send godkjent melding
    System -> Grensesnitt: Vis godkjent melding

    else Error
    Database -> System: ERROR
    deactivate Database
    System -> Grensesnitt: Send ERROR
    Grensesnitt -> User: Vis ERROR
    end
else ERROR
    System -> Grensesnitt: Send ERROR
    deactivate System
    Grensesnitt -> User: Vis ERROR
    deactivate Grensesnitt
end
@enduml