@startuml
actor User
database Database

User -> System: Registrer for gitt arrangement
System -> System: Valider forespørsel

alt Suksess
    System -> Database: Lagre registrering
    alt Suksess
    Database -> System: Suksess
    else Error
    Database -> System: ERROR
    System -> User: Vis ERROR
    end
else ERROR
    System -> User: Vis ERROR
end
@enduml