@startuml
actor Bruker
participant Grensesnitt
participant System
database Database

Bruker -> Grensesnitt: Bli med på valgt arrangement
activate Grensesnitt
Grensesnitt -> System: Registrer Bruker for gitt arrangement
activate System
System -> System: Valider forespørsel

alt Suksess
    System -> Database: Lagre registrering
    activate Database
    alt Suksess
    Database -> System: Suksess
    System --> Bruker: send push notifikasjon
    System --> Bruker: Send verifikasjons mail
    System -> Grensesnitt: Send godkjent melding
    System -> Grensesnitt: Vis godkjent melding

    else Error
    Database -> System: ERROR
    deactivate Database
    System -> Grensesnitt: Send ERROR
    Grensesnitt -> Bruker: Vis ERROR
    end
else ERROR
    System -> Grensesnitt: Send ERROR
    deactivate System
    Grensesnitt -> Bruker: Vis ERROR
    deactivate Grensesnitt
end
@enduml